// The circuit editor's public surface: the pure cores it is built from, in full.
//
// The page (`main.ts`, loaded by `circuit_editor.html`) is deliberately NOT
// re-exported: it is an entry point, not a module anything imports. Nor are its
// DOM consumers (`shell.ts`, `dock.ts`, `preview3d.ts` and the `panel_*`
// family), which are structure over the cores below and have nothing a test or
// another module wants.
//
// It is re-exported IN FULL on purpose, and `tests/editor_circuit_index.test.ts`
// pins that both ways: a core export missing here is a piece of the declared
// public surface nothing can reach, and a DOM module leaking in here would make
// the split above a comment rather than a contract.
//
// The readout every drag is measured against is not here either. It lives in
// `src/sim/realm_racers_circuit_metrics.ts`, because it is the same validation a
// content test runs over every shipped circuit and a copy of it in a dev tool
// would be a rule the game does not share.

export {
  DRAFT_ID_RE,
  type DraftDeleteDecision,
  type DraftEndpointResponse,
  type DraftFile,
  type DraftListEntry,
  type DraftReader,
  draftDeleteDecision,
  draftListResponse,
  draftResponse,
} from './draft_endpoints_core';
export {
  type DiskDraftRow,
  DRAFT_SAVE_DEBOUNCE_MS,
  DRAFT_STORAGE_KEY,
  diskDraftRows,
  draftAgeText,
  parseDraft,
  parseThumbnailCache,
  resumeOfferText,
  type StoredDraft,
  serializeDraft,
  shouldWarnOnUnload,
  THUMBNAIL_STORAGE_KEY,
} from './draft_store_core';
export {
  CHROME_ONLY_ICONS,
  EDITOR_ICONS,
  type EditorIconId,
  editorIcon,
} from './editor_icons';
export { type EnvelopeSuggestion, suggestEnvelope } from './envelope_core';
export {
  circuitFromTypeScript,
  circuitToTypeScript,
  draftFileContents,
  roundCircuit,
  validateCircuitPayload,
} from './export_core';
export {
  type CircuitBand,
  deleteControlPoint,
  FRACTION_SNAP,
  fromWidthBands,
  hitTestControlPoint,
  insertControlPoint,
  MIN_CONTROL_POINTS,
  moveControlPoint,
  nearestSegment,
  type PaintBandOptions,
  paintSpan,
  type SegmentHit,
  toWidthBands,
} from './handles_core';
export { HISTORY_CAP, SnapshotHistory } from './history_core';
export {
  type ActionId,
  type ActionScope,
  actionChord,
  actionForSelectionShortcut,
  actionForShortcut,
  actionTooltip,
  autoSideTab,
  CALLOUT_MIN_GAP,
  CALLOUT_REACH,
  type CalloutAnchor,
  type CalloutSpreadOptions,
  type CheatBlock,
  type ChipTone,
  type CircuitTool,
  calloutProblems,
  cheatBlocks,
  chordHints,
  clampDock,
  clampScale,
  clampToolValue,
  clampZoom,
  DEFAULT_LAYOUT,
  DOCK_MIN_HEIGHT,
  DOCK_MIN_WIDTH,
  DOCK_SCRUB_STEPS,
  type DockGeometry,
  defaultDock,
  EDITOR_ACTIONS,
  type EditorActionDef,
  type EditorLayout,
  editorAction,
  formatShortcut,
  GRID_YARDS,
  gridRange,
  gridStepAt,
  type HeadlineChip,
  headlineChips,
  LAYOUT_STORAGE_KEY,
  MAX_CANVAS_CALLOUTS,
  MAX_GRID_LINES,
  MENU_ITEMS,
  MENUS,
  type MenuId,
  MODE_ACTIONS,
  menuActions,
  type PlacementMode,
  type PlanArea,
  PREVIEW_READY_TITLES,
  PROBLEM_LABELS,
  type PreviewReadyState,
  type ProblemsChip,
  parseLayout,
  problemDetail,
  problemHeadline,
  problemsChip,
  RAIL_ACTION_IDS,
  RAIL_MODES,
  type RailModeDef,
  type RailModeId,
  railActions,
  railBanner,
  type ShortcutEvent,
  type ShortcutPlatform,
  SIDE_TAB_LABELS,
  SIDE_TABS_MIN,
  type SideTabId,
  serializeLayout,
  shortcutMatches,
  sideTabsFor,
  snapPoint,
  snapValue,
  spreadCallouts,
  TOOL_VALUE_FIELDS,
  type ToolValueField,
  toolFor,
  ZOOM_MAX_SCALE,
  ZOOM_MIN_SCALE,
  ZOOM_REFERENCE_SCALE,
  zoomPercent,
  zoomScale,
} from './layout_core';
export {
  filterLibrary,
  LIBRARY_ALL_CATEGORY,
  LIBRARY_DEFAULT_CATEGORY,
  LIBRARY_THEME_CATEGORY,
  type LibraryCategory,
  type LibraryFilter,
  libraryCategories,
  libraryCategoryExists,
  libraryEmptyText,
  librarySearchPlaceholder,
} from './library_core';
export {
  armStateText,
  CIRCUIT_ONLY_ACTIONS,
  MAX_LISTED_PROBLEMS,
  MODE_READOUT,
  needsCircuit,
  type PanelInputs,
  type PanelState,
  panelLayout,
  READOUT_SECTIONS,
  type ReadoutSection,
} from './panel_core';
export {
  addPickupRow,
  MAX_PICKUP_ROWS,
  PICKUP_ROW_MIN_GAP,
  type PickupRowAdd,
  type PickupRowAddOutcome,
  pickupRowAtPoint,
  pickupRowFractionAt,
  removedPickupRow,
} from './pickup_rows_core';
export {
  ALONG_ROAD_MAX_PIECES,
  ALONG_ROAD_MIN_SPACING,
  type AlongRoadOptions,
  type AlongRoadRun,
  alongRoadProps,
  lapPositionAt,
  lateralAt,
  type PendingYaw,
  type PlacementLegality,
  pendingYawText,
  placementLegality,
  pressWasDrag,
  ROAD_EDGE_CLEARANCE,
  ROAD_EDGE_SNAP_BAND,
  resolveSnap,
  rotatedPendingYaw,
  SCATTER_MIN_SPACING,
  type SnapKind,
  type SnapOptions,
  type SnapResult,
  spacingFloor,
  TILE_DRAG_SLOP,
} from './placement_core';
export {
  FIT_MARGIN_BLANK,
  FIT_MARGIN_DRAWN,
  fitHalfExtent,
  fitScale,
  HIT_TOLERANCE_PIXELS,
  labelledPieces,
  PLAN_PALETTE_FALLBACK,
  PLAN_PALETTE_VARS,
  type PlanLimits,
  type PlanPaletteId,
  PROP_LABEL_MIN_GAP,
  PROP_LABEL_MIN_SCALE,
  planLimits,
  resolvePlanPalette,
  STARTER_OVAL,
  starterControlPoints,
  WHEEL_ZOOM_STEP,
  wheelZoomScale,
  withAlpha,
} from './plan_core';
export {
  advanceFlyThrough,
  circuitLocalSample,
  createFlyLook,
  createPreviewOrbit,
  FLY_LOOK_MAX_PITCH,
  flyLookDrag,
  flyLookPose,
  flySpeedYardsPerSecond,
  flyThroughPose,
  flyThroughPoseAt,
  orbitDrag,
  orbitFrame,
  orbitLookAt,
  orbitPan,
  orbitPose,
  orbitZoom,
  PREVIEW_CHASE_PROFILE,
  PREVIEW_FLY_SPEED_FRACTIONS,
  PREVIEW_ORBIT_LIMITS,
  PREVIEW_PAN_LIMIT,
  PREVIEW_REBUILD_DEBOUNCE_MS,
  type PreviewChaseProfile,
  type PreviewFlyLook,
  type PreviewFlySpeed,
  type PreviewOrbitState,
  type PreviewPoint,
  type PreviewPose,
  type PreviewTrackSampler,
} from './preview_camera_core';
export {
  type AuthoredPlacement,
  authorPlacement,
  clampPropScale,
  convertedProp,
  type DressingRect,
  type DressingSelection,
  DUPLICATE_OFFSET_YD,
  duplicatedPond,
  duplicatedProp,
  GHOST_ID_SUFFIX,
  ghostPlacement,
  ghostRowPlacements,
  hitTestPlaced,
  hitTestPondHandle,
  hitTestPonds,
  hitTestPropHandle,
  movedProp,
  nextSeed,
  nudgeKeyOf,
  PALETTE_GROUPS,
  POND_CHOICE,
  POND_HANDLES,
  POND_MIN_RADIUS,
  POND_ROTATE_HANDLE_GAP,
  type PondHandle,
  PROP_HANDLES,
  PROP_ROTATE_HANDLE_GAP,
  PROP_TRACK_SPACE_BAND,
  type PropFrame,
  type PropHandle,
  type PropPaletteEntry,
  placedPropIndices,
  placementIndexOf,
  planNudge,
  pondFromDrag,
  pondHandlePoints,
  pondWithHandleAt,
  propFrameOf,
  propHandlePoints,
  propPalette,
  propProjectionHint,
  propScaleInRange,
  propWithHandleAt,
  removedAt,
  replacedAt,
  rotatedProp,
  scaledProp,
  scatterFromRect,
  selectionFocusPoint,
  tangentProp,
  toggledCollide,
} from './props_core';
export {
  fitStrokeToControlPoints,
  perpendicularDistance,
  resampleClosed,
  type StrokeFitOptions,
} from './stroke_fit_core';
export {
  THUMBNAIL_MARGIN,
  THUMBNAIL_MIN_DISTANCE,
  THUMBNAIL_PITCH,
  THUMBNAIL_YAW,
  type ThumbnailBounds,
  type ThumbnailPoint,
  type ThumbnailPose,
  thumbnailBoundsUsable,
  thumbnailOwnsGeometry,
  thumbnailPose,
} from './thumbnail_core';
export { suggestWidthBands, type WidthFixResult } from './width_fix_core';
