import type { RiftInstance } from './types';

/** Fresh pool slot. Each slot owns its mutable collections until the run reuses it. */
export function createRiftInstance(slot: number): RiftInstance {
  return {
    slot,
    instanceId: 0,
    eventId: null,
    partyKey: null,
    memberIds: new Set(),
    startedAt: 0,
    finishedAt: null,
    outcome: 'abandoned',
    upgrade: null,
    seed: 0,
    baseLevel: 1,
    floorIndex: 0,
    floorCount: 0,
    mobIds: [],
    objectIds: [],
    bossId: null,
    bossDiedAtTick: null,
    exitId: null,
    descentAt: null,
    descentId: null,
    descentOpen: false,
    pylonIds: [],
    litPylons: new Set(),
    pylonTotal: 0,
    puzzleSolved: false,
    boulderIds: [],
    boulderPads: [],
    seqRuneIds: [],
    seqStep: 0,
    beaconId: null,
    rollerIds: [],
    cacheId: null,
    lockpick: null,
    gateId: null,
    switchId: null,
    gateOpen: true,
    minibossId: null,
    orbId: null,
    orbActive: false,
    returnPos: { x: 0, z: 0 },
    emptyFor: 0,
    tier: null,
    portalId: null,
    rewarded: false,
    vault: null,
    progressed: false,
    seqResetAt: -Infinity,
    bossDeathZones: [],
  };
}
