import { describe, expect, it } from 'vitest';
import { computeAbilityVfxSnapshot, readCommittedSnapshot } from '../scripts/ability_vfx_snapshot';
import { ABILITY_VFX_FULL_SPECS } from '../src/render/ability_vfx_full_specs';
import { abilityVfxFullSpec } from '../src/render/ability_vfx_registry';
import { WARRIOR_BASE_PROFILES } from '../src/render/warrior_base_profiles';
import { WARRIOR_CHOREOGRAPHY } from '../src/render/warrior_vfx_specs';
import { ABILITIES } from '../src/sim/data';

// The Warrior VFX integration (release44) is only allowed to touch WARRIOR
// abilities. Comparing the live registry against a second copy of the SAME
// live imports (the old helpers/release44_ability_vfx_reference.ts) is a
// vacuous X === X pin: both sides resolve to the identical object from the
// identical import, so the assertion cannot fail no matter what changed.
// Instead this suite compares against a COMMITTED snapshot of sha256 hashes
// (tests/helpers/ability_vfx_snapshot.json, generated by
// scripts/ability_vfx_snapshot.ts from the release base tables), which is
// data checked in at a point in time and is blind to whatever the live
// tables say today.
const snapshot = readCommittedSnapshot();
const current = computeAbilityVfxSnapshot();

describe('Warrior-only release44 integration', () => {
  it('leaves every other class resolved on the committed release44 VFX snapshot', () => {
    let checked = 0;
    for (const [id, ability] of Object.entries(ABILITIES)) {
      if (ability.class === 'warrior') continue;
      const committed = snapshot.abilities[id];
      expect(
        committed,
        `'${id}' is missing from tests/helpers/ability_vfx_snapshot.json; regenerate with ` +
          `npx tsx scripts/ability_vfx_snapshot.ts --write`,
      ).toBeDefined();
      const live = current.abilities[id];
      expect(live.spec, `${id}: compact VFX spec hash drifted from the release44 snapshot`).toBe(
        committed.spec,
      );
      expect(live.full, `${id}: full VFX spec hash drifted from the release44 snapshot`).toBe(
        committed.full,
      );
      checked++;
    }
    // The real count is ~355; a floor near it (not the trivial >100 a
    // silently-empty loop would still clear) proves the loop actually ran
    // over the whole non-warrior roster.
    expect(checked).toBeGreaterThan(300);
  });

  it('never lets a warrior spec shadow a non-warrior ability id', () => {
    for (const id of Object.keys(WARRIOR_CHOREOGRAPHY)) {
      expect(ABILITIES[id]?.class, id).toBe('warrior');
    }
  });

  it('pins the authored WARRIOR_CHOREOGRAPHY motion for every reviewed ability', () => {
    const committedIds = Object.keys(snapshot.warriorChoreography).sort();
    const liveIds = Object.keys(WARRIOR_CHOREOGRAPHY).sort();
    expect(liveIds).toEqual(committedIds);
    for (const id of liveIds) {
      expect(current.warriorChoreography[id], id).toBe(snapshot.warriorChoreography[id]);
    }
  });

  it('selects the authored physical choreography for every reviewed Warrior ability', () => {
    for (const [id, physical] of Object.entries(WARRIOR_CHOREOGRAPHY)) {
      expect(ABILITIES[id]?.class, id).toBe('warrior');
      expect(abilityVfxFullSpec(id)?.physical, id).toBe(physical);
      expect(abilityVfxFullSpec(id)?.windupStyle, id).toBe('none');
    }
  });
});

// warrior_base_profiles.ts is the generated gallery row plus one authored `filler`
// bit per ability (it used to be a 1485-line copy of those rows). A choreography
// id without a profile silently falls back to a dash/physical stub in
// warrior_vfx_specs.ts, so every authored id must have a real generated base,
// and a profile may differ from its generated row in nothing but `filler`.
describe('warrior base profiles are the generated rows plus filler', () => {
  it('gives every authored choreography id a profile built from its generated row', () => {
    for (const id of Object.keys(WARRIOR_CHOREOGRAPHY)) {
      const generated = ABILITY_VFX_FULL_SPECS[id];
      const profile = WARRIOR_BASE_PROFILES[id];
      if (!generated) {
        // No gallery row at all (Intervene): the documented fallback in
        // warrior_vfx_specs.ts applies, and no profile may invent one.
        expect(profile, `'${id}' has a profile but no generated row`).toBeUndefined();
        continue;
      }
      expect(
        profile,
        `'${id}' has no WARRIOR_FILLER entry (warrior_base_profiles.ts)`,
      ).toBeDefined();
      const { filler, ...rest } = profile;
      expect(typeof filler).toBe('boolean');
      expect(rest).toEqual(generated);
    }
  });
  it('profiles only warrior abilities', () => {
    for (const id of Object.keys(WARRIOR_BASE_PROFILES)) {
      expect(ABILITIES[id]?.class, id).toBe('warrior');
    }
  });
});
