// The producers of the game's GLSL, hashed, so a committed shader corpus can
// say whether it still describes this checkout (tests/shader_corpus_freshness.test.ts).
//
// The corpus is recorded from a live browser session on a real GPU
// (scripts/shader_corpus_record.mjs), which no build step can run, so it is
// COMMITTED and regenerated by hand; this hash is what tells a stale one from a
// fresh one. The producer list is a RULE over the tree rather than a hand list
// that rots: three itself (its version, and the repo's patch of it, which
// carries the dry-compile hunk), plus every source under src/render whose text
// produces or edits shader code (a ShaderMaterial, an onBeforeCompile splice,
// a GLSL chunk include, or a glsl tag). A render edit outside that rule does
// not touch the GLSL and must not demand a real-GPU regen.

import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

/** A file is a shader producer when its text carries one of these. */
export const SHADER_PRODUCER_PATTERN =
  /ShaderMaterial|onBeforeCompile|#include\s*<|\bglsl\b|gl_FragColor|pc_fragColor/;

export const SHADER_PRODUCER_ROOT = 'src/render';

function walk(dir, out) {
  for (const name of readdirSync(dir).sort()) {
    const path = join(dir, name);
    if (statSync(path).isDirectory()) walk(path, out);
    else if (name.endsWith('.ts') && !name.endsWith('.d.ts')) out.push(path);
  }
  return out;
}

/** Every producer path under the repo root, repo-relative, sorted, slash-separated. */
export function listShaderProducers(repoRoot) {
  const root = join(repoRoot, SHADER_PRODUCER_ROOT);
  const files = walk(root, []);
  const producers = [];
  for (const path of files) {
    if (SHADER_PRODUCER_PATTERN.test(readFileSync(path, 'utf8'))) {
      producers.push(relative(repoRoot, path).split(sep).join('/'));
    }
  }
  return producers;
}

/** The three version this checkout pins, from package.json. */
export function threeVersion(repoRoot) {
  const pkg = JSON.parse(readFileSync(join(repoRoot, 'package.json'), 'utf8'));
  return String(pkg.dependencies?.three ?? pkg.devDependencies?.three ?? '');
}

/** The repo's three patch files, repo-relative, sorted. */
export function listThreePatches(repoRoot) {
  const dir = join(repoRoot, 'patches');
  return readdirSync(dir)
    .filter((name) => name.startsWith('three@') && name.endsWith('.patch'))
    .sort()
    .map((name) => `patches/${name}`);
}

/**
 * A producer's text with what cannot change the GLSL removed: block and line
 * comments, and runs of whitespace. A formatter pass or a reworded comment
 * over a producer must not demand a real-GPU regen; a token change must.
 * (A `//` inside a string is stripped too: this is a hash input, not code.)
 */
export function normalizeProducerText(text) {
  return text
    .replace(/\/\*[\s\S]*?\*\//g, ' ')
    .replace(/(^|[^:\\])\/\/[^\n]*/g, '$1')
    .replace(/\s+/g, ' ')
    .trim();
}

/**
 * One sha256 over the producers: the three version, each patch's text, and
 * each producer file's path and NORMALIZED text, in a fixed order. Stable
 * across machines and platforms (paths are slash-separated, the
 * normalization erases line-ending and formatting differences).
 */
export function hashShaderCorpusInputs(repoRoot) {
  const hash = createHash('sha256');
  hash.update(`three@${threeVersion(repoRoot)}\n`);
  for (const patch of listThreePatches(repoRoot)) {
    hash.update(`${patch}\n`);
    hash.update(normalizeProducerText(readFileSync(join(repoRoot, patch), 'utf8')));
    hash.update('\n');
  }
  for (const producer of listShaderProducers(repoRoot)) {
    hash.update(`${producer}\n`);
    hash.update(normalizeProducerText(readFileSync(join(repoRoot, producer), 'utf8')));
    hash.update('\n');
  }
  return hash.digest('hex');
}
