import {
  type CannonActionDef,
  type CannonActionId,
  type CannonEnemyDef,
  type CannonEnemyKind,
  type CannonSpawnDef,
  TICK_RATE,
} from '../types';

// Prototype minigame tuning, independent of class spells, gear and resources.
export const CANNON_ACTIONS: Readonly<Record<CannonActionId, Readonly<CannonActionDef>>> = {
  cannonball: {
    damage: 100,
    radius: 6,
    cooldownTicks: 2 * TICK_RATE,
    flightTicks: 16,
    slowTicks: 0,
    slowMultiplier: 1,
    burnTicks: 0,
    burnDamage: 0,
  },
  grapeshot: {
    damage: 60,
    radius: 9,
    cooldownTicks: 6 * TICK_RATE,
    flightTicks: 16,
    slowTicks: 3 * TICK_RATE,
    slowMultiplier: 0.5,
    burnTicks: 0,
    burnDamage: 0,
  },
  incendiary: {
    damage: 30,
    radius: 7,
    cooldownTicks: 12 * TICK_RATE,
    flightTicks: 16,
    slowTicks: 0,
    slowMultiplier: 1,
    burnTicks: 5 * TICK_RATE,
    burnDamage: 30,
  },
};

// Breach damage is the cannon's effective health bar (integrity is a 0..100
// percent on the wire and the HUD). Playtest feedback: a single commander reaching
// the line one-shot the emplacement, so no breach may end a healthy run on its own;
// the commander now costs 60 and the rest scale down with it.
export const CANNON_ENEMIES: Readonly<Record<CannonEnemyKind, Readonly<CannonEnemyDef>>> = {
  infantry: { hp: 100, speed: 2.1, breachDamage: 7 },
  runner: { hp: 80, speed: 3.78, breachDamage: 8 },
  armored: { hp: 220, speed: 1.4, breachDamage: 12 },
  commander: { hp: 800, speed: 0.98, breachDamage: 60 },
  sapper: { hp: 80, speed: 4.2, breachDamage: 25 },
};

export const CANNON_TACTICS = {
  barrelRadius: 8,
  barrelDamage: 180,
  armorReduction: 0.5,
  exposedFireMultiplier: 2,
  chargeHealthFraction: 0.65,
  commanderChargeSpeed: 1.8,
  troopChargeSpeed: 1.25,
  feedbackTicks: 20,
  feedbackLimit: 64,
  goldIntegrity: 95,
  goldAccuracy: 0.8,
  silverIntegrity: 60,
  silverAccuracy: 0.5,
} as const;

export const CANNON_BARREL_PLACEMENTS = [
  { lane: 0.25, depth: 0.5 },
  { lane: 0.5, depth: 0.5 },
  { lane: 0.75, depth: 0.5 },
] as const;

// Preserve both flanks in wave two; the final wave has only the central barrel.
export const CANNON_WAVE_BARREL_INDICES = [[0, 1, 2], [0, 2], [1]] as const;

// Lanes are normalized across the field; authored order is spawn order.
// Wave one uses exact 20 Hz ticks: its original 8/18/32-second groups are 15% earlier.
export const CANNON_WAVES: readonly (readonly CannonSpawnDef[])[] = [
  [
    { atTick: 0, lane: 0.4, kind: 'infantry' },
    { atTick: 0, lane: 0.44, kind: 'infantry' },
    { atTick: 0, lane: 0.48, kind: 'infantry' },
    { atTick: 0, lane: 0.52, kind: 'infantry' },
    { atTick: 0, lane: 0.56, kind: 'infantry' },
    { atTick: 0, lane: 0.6, kind: 'infantry' },
    { atTick: 136, lane: 0.4, kind: 'infantry' },
    { atTick: 136, lane: 0.44, kind: 'infantry' },
    { atTick: 136, lane: 0.48, kind: 'infantry' },
    { atTick: 136, lane: 0.52, kind: 'infantry' },
    { atTick: 136, lane: 0.56, kind: 'infantry' },
    { atTick: 136, lane: 0.6, kind: 'infantry' },
    { atTick: 306, lane: 0.34, kind: 'infantry' },
    { atTick: 306, lane: 0.38, kind: 'infantry' },
    { atTick: 306, lane: 0.42, kind: 'infantry' },
    { atTick: 306, lane: 0.46, kind: 'infantry' },
    { atTick: 306, lane: 0.5, kind: 'infantry' },
    { atTick: 306, lane: 0.54, kind: 'infantry' },
    { atTick: 306, lane: 0.62, kind: 'infantry' },
    { atTick: 306, lane: 0.58, kind: 'infantry' },
    { atTick: 306, lane: 0.66, kind: 'infantry' },
    { atTick: 544, lane: 0.4, kind: 'infantry' },
    { atTick: 544, lane: 0.44, kind: 'infantry' },
    { atTick: 544, lane: 0.48, kind: 'infantry' },
    { atTick: 544, lane: 0.52, kind: 'infantry' },
    { atTick: 544, lane: 0.56, kind: 'infantry' },
    { atTick: 544, lane: 0.6, kind: 'infantry' },
  ],
  [
    { atTick: 0, lane: 0.2, kind: 'infantry' },
    { atTick: 0, lane: 0.24, kind: 'infantry' },
    { atTick: 0, lane: 0.28, kind: 'infantry' },
    { atTick: 0, lane: 0.32, kind: 'infantry' },
    { atTick: 6 * TICK_RATE, lane: 0.18, kind: 'armored' },
    { atTick: 6 * TICK_RATE, lane: 0.22, kind: 'armored' },
    { atTick: 6 * TICK_RATE, lane: 0.74, kind: 'sapper' },
    { atTick: 6 * TICK_RATE, lane: 0.78, kind: 'runner' },
    { atTick: 6 * TICK_RATE, lane: 0.82, kind: 'runner' },
    { atTick: 10 * TICK_RATE, lane: 0.44, kind: 'infantry' },
    { atTick: 10 * TICK_RATE, lane: 0.48, kind: 'infantry' },
    { atTick: 10 * TICK_RATE, lane: 0.52, kind: 'infantry' },
    { atTick: 10 * TICK_RATE, lane: 0.56, kind: 'infantry' },
    { atTick: 10 * TICK_RATE, lane: 0.6, kind: 'infantry' },
    { atTick: 10 * TICK_RATE, lane: 0.64, kind: 'infantry' },
    { atTick: 16 * TICK_RATE, lane: 0.18, kind: 'runner' },
    { atTick: 16 * TICK_RATE, lane: 0.22, kind: 'runner' },
    { atTick: 16 * TICK_RATE, lane: 0.26, kind: 'runner' },
    { atTick: 24 * TICK_RATE, lane: 0.68, kind: 'infantry' },
    { atTick: 24 * TICK_RATE, lane: 0.72, kind: 'infantry' },
    { atTick: 24 * TICK_RATE, lane: 0.76, kind: 'infantry' },
    { atTick: 24 * TICK_RATE, lane: 0.8, kind: 'infantry' },
    { atTick: 24 * TICK_RATE, lane: 0.84, kind: 'infantry' },
    { atTick: 24 * TICK_RATE, lane: 0.88, kind: 'infantry' },
    { atTick: 32 * TICK_RATE, lane: 0.46, kind: 'runner' },
    { atTick: 32 * TICK_RATE, lane: 0.5, kind: 'runner' },
    { atTick: 32 * TICK_RATE, lane: 0.54, kind: 'runner' },
    { atTick: 38 * TICK_RATE, lane: 0.18, kind: 'armored' },
    { atTick: 38 * TICK_RATE, lane: 0.22, kind: 'armored' },
    { atTick: 38 * TICK_RATE, lane: 0.26, kind: 'runner' },
    { atTick: 38 * TICK_RATE, lane: 0.74, kind: 'sapper' },
    { atTick: 38 * TICK_RATE, lane: 0.78, kind: 'runner' },
    { atTick: 38 * TICK_RATE, lane: 0.82, kind: 'runner' },
  ],
  [
    { atTick: 0, lane: 0.18, kind: 'armored' },
    { atTick: 0, lane: 0.22, kind: 'armored' },
    { atTick: 0, lane: 0.26, kind: 'armored' },
    { atTick: 0, lane: 0.74, kind: 'armored' },
    { atTick: 0, lane: 0.78, kind: 'armored' },
    { atTick: 0, lane: 0.82, kind: 'armored' },
    { atTick: 8 * TICK_RATE, lane: 0.4, kind: 'infantry' },
    { atTick: 8 * TICK_RATE, lane: 0.44, kind: 'infantry' },
    { atTick: 8 * TICK_RATE, lane: 0.48, kind: 'infantry' },
    { atTick: 8 * TICK_RATE, lane: 0.52, kind: 'infantry' },
    { atTick: 8 * TICK_RATE, lane: 0.56, kind: 'infantry' },
    { atTick: 8 * TICK_RATE, lane: 0.6, kind: 'infantry' },
    { atTick: 16 * TICK_RATE, lane: 0.5, kind: 'commander' },
    { atTick: 16 * TICK_RATE, lane: 0.38, kind: 'armored' },
    { atTick: 16 * TICK_RATE, lane: 0.62, kind: 'armored' },
    { atTick: 16 * TICK_RATE, lane: 0.74, kind: 'sapper' },
    { atTick: 22 * TICK_RATE, lane: 0.22, kind: 'runner' },
    { atTick: 22 * TICK_RATE, lane: 0.26, kind: 'runner' },
    { atTick: 28 * TICK_RATE, lane: 0.74, kind: 'runner' },
    { atTick: 28 * TICK_RATE, lane: 0.78, kind: 'runner' },
    { atTick: 28 * TICK_RATE, lane: 0.82, kind: 'runner' },
    { atTick: 34 * TICK_RATE, lane: 0.26, kind: 'armored' },
    { atTick: 34 * TICK_RATE, lane: 0.74, kind: 'armored' },
    { atTick: 34 * TICK_RATE, lane: 0.78, kind: 'armored' },
    { atTick: 34 * TICK_RATE, lane: 0.82, kind: 'armored' },
    { atTick: 42 * TICK_RATE, lane: 0.4, kind: 'infantry' },
    { atTick: 42 * TICK_RATE, lane: 0.44, kind: 'infantry' },
    { atTick: 42 * TICK_RATE, lane: 0.48, kind: 'infantry' },
    { atTick: 42 * TICK_RATE, lane: 0.52, kind: 'infantry' },
    { atTick: 42 * TICK_RATE, lane: 0.56, kind: 'infantry' },
    { atTick: 42 * TICK_RATE, lane: 0.6, kind: 'infantry' },
  ],
];
