// Warfare Season 2 ("Vanguard"): the top tier of honor gear, sold beside the
// Warfare entry tier (content/pvp_honor.ts) by both honor quartermasters. One
// five-piece set per spec (27 sets, the raid sets' slots and 2/4 thresholds)
// plus four weapons. Built once from docs/design/warfare-season-2.md (names) and
// the named rules below by a one-off script, and maintained by hand from here:
// tests/warfare_season2.test.ts pins every rule, so an edit that breaks one
// fails there. The design doc is the review record.
//
// Every piece reads item level 35 (SEASON2_SOURCE_LEVEL 29 + the epic bump 6),
// level with the Ignivar raid tier, and keeps the honor discount so honor gear
// is never the raid pick in PvE (docs/design/warfare-season-2.md, "The PvE
// promise"):
//   - the stat line is SEASON2_STAT_FRACTION of the item-level-35 budget, with
//     stamina lifted to the FULL budget's stamina floor (the entry tier's rule):
//     a physical piece carries floor stamina and the rest of the line as
//     Strength or Agility, a caster piece the whole line as Intellect and
//     Spirit with floor stamina on top;
//   - no hit, crit or haste rating on any piece;
//   - armor is SEASON2_ARMOR_FRACTION of the mean armor of same-slot,
//     same-armor-type item-level-35 raid set pieces;
//   - Warfare Offense and Defense Rating equal the full slot budget, as on the
//     entry tier, so the existing caps bound every total.
// Sets are class-locked (requiredClass); their bonuses live in
// content/vanguard_item_sets.ts (text) and content/vanguard_set_bonuses.ts
// (engine rows). Pinned by tests/warfare_season2.test.ts.

import type { ItemDef } from '../types';

export const SEASON2_SOURCE_LEVEL = 29;
export const SEASON2_STAT_FRACTION = 0.9;
export const SEASON2_ARMOR_FRACTION = 0.9;
/** Warfare ratings per piece, as multiples of the slot budget (the entry tier
 *  carries 1x). Season 2 bonuses change abilities rather than add rating, so the
 *  pieces carry it instead: a Season 2 kit (the five pieces plus entry-tier
 *  waist, feet, jewelry and weapon) reaches the 30 percent Offense and Defense
 *  caps and the +80 percent Vitality cap, where a full Season 1 kit stops at
 *  +50 percent. None of it applies in dungeons or raids. */
export const SEASON2_OFFENSE_RATING_MULT = 2.2;
export const SEASON2_DEFENSE_RATING_MULT = 3.4;
export const SEASON2_ARMOR_SLOTS = ['helmet', 'shoulder', 'chest', 'legs', 'gloves'] as const;
export const SEASON2_PRICES: Readonly<Record<string, number>> = {
  helmet: 1350,
  shoulder: 1050,
  chest: 1800,
  legs: 1575,
  gloves: 825,
};
export const SEASON2_WEAPON_PRICE = 1800;

/** One Season 2 set per spec, in class then spec order (the shop reads this). */
export interface Season2Set {
  setId: string;
  cls: string;
  spec: string;
  armorType: 'cloth' | 'leather' | 'mail';
  itemIds: readonly string[];
}

export const SEASON2_SETS: readonly Season2Set[] = [
  {
    setId: 'vanguard_warrior_arms',
    cls: 'warrior',
    spec: 'arms',
    armorType: 'mail',
    itemIds: [
      'vanguard_warrior_arms_helmet',
      'vanguard_warrior_arms_shoulder',
      'vanguard_warrior_arms_chest',
      'vanguard_warrior_arms_legs',
      'vanguard_warrior_arms_gloves',
    ],
  },
  {
    setId: 'vanguard_warrior_fury',
    cls: 'warrior',
    spec: 'fury',
    armorType: 'mail',
    itemIds: [
      'vanguard_warrior_fury_helmet',
      'vanguard_warrior_fury_shoulder',
      'vanguard_warrior_fury_chest',
      'vanguard_warrior_fury_legs',
      'vanguard_warrior_fury_gloves',
    ],
  },
  {
    setId: 'vanguard_warrior_prot',
    cls: 'warrior',
    spec: 'prot',
    armorType: 'mail',
    itemIds: [
      'vanguard_warrior_prot_helmet',
      'vanguard_warrior_prot_shoulder',
      'vanguard_warrior_prot_chest',
      'vanguard_warrior_prot_legs',
      'vanguard_warrior_prot_gloves',
    ],
  },
  {
    setId: 'vanguard_paladin_holy',
    cls: 'paladin',
    spec: 'holy',
    armorType: 'mail',
    itemIds: [
      'vanguard_paladin_holy_helmet',
      'vanguard_paladin_holy_shoulder',
      'vanguard_paladin_holy_chest',
      'vanguard_paladin_holy_legs',
      'vanguard_paladin_holy_gloves',
    ],
  },
  {
    setId: 'vanguard_paladin_protection',
    cls: 'paladin',
    spec: 'protection',
    armorType: 'mail',
    itemIds: [
      'vanguard_paladin_protection_helmet',
      'vanguard_paladin_protection_shoulder',
      'vanguard_paladin_protection_chest',
      'vanguard_paladin_protection_legs',
      'vanguard_paladin_protection_gloves',
    ],
  },
  {
    setId: 'vanguard_paladin_retribution',
    cls: 'paladin',
    spec: 'retribution',
    armorType: 'mail',
    itemIds: [
      'vanguard_paladin_retribution_helmet',
      'vanguard_paladin_retribution_shoulder',
      'vanguard_paladin_retribution_chest',
      'vanguard_paladin_retribution_legs',
      'vanguard_paladin_retribution_gloves',
    ],
  },
  {
    setId: 'vanguard_hunter_beast_mastery',
    cls: 'hunter',
    spec: 'beast_mastery',
    armorType: 'leather',
    itemIds: [
      'vanguard_hunter_beast_mastery_helmet',
      'vanguard_hunter_beast_mastery_shoulder',
      'vanguard_hunter_beast_mastery_chest',
      'vanguard_hunter_beast_mastery_legs',
      'vanguard_hunter_beast_mastery_gloves',
    ],
  },
  {
    setId: 'vanguard_hunter_marksmanship',
    cls: 'hunter',
    spec: 'marksmanship',
    armorType: 'leather',
    itemIds: [
      'vanguard_hunter_marksmanship_helmet',
      'vanguard_hunter_marksmanship_shoulder',
      'vanguard_hunter_marksmanship_chest',
      'vanguard_hunter_marksmanship_legs',
      'vanguard_hunter_marksmanship_gloves',
    ],
  },
  {
    setId: 'vanguard_hunter_survival',
    cls: 'hunter',
    spec: 'survival',
    armorType: 'leather',
    itemIds: [
      'vanguard_hunter_survival_helmet',
      'vanguard_hunter_survival_shoulder',
      'vanguard_hunter_survival_chest',
      'vanguard_hunter_survival_legs',
      'vanguard_hunter_survival_gloves',
    ],
  },
  {
    setId: 'vanguard_rogue_assassination',
    cls: 'rogue',
    spec: 'assassination',
    armorType: 'leather',
    itemIds: [
      'vanguard_rogue_assassination_helmet',
      'vanguard_rogue_assassination_shoulder',
      'vanguard_rogue_assassination_chest',
      'vanguard_rogue_assassination_legs',
      'vanguard_rogue_assassination_gloves',
    ],
  },
  {
    setId: 'vanguard_rogue_combat',
    cls: 'rogue',
    spec: 'combat',
    armorType: 'leather',
    itemIds: [
      'vanguard_rogue_combat_helmet',
      'vanguard_rogue_combat_shoulder',
      'vanguard_rogue_combat_chest',
      'vanguard_rogue_combat_legs',
      'vanguard_rogue_combat_gloves',
    ],
  },
  {
    setId: 'vanguard_rogue_subtlety',
    cls: 'rogue',
    spec: 'subtlety',
    armorType: 'leather',
    itemIds: [
      'vanguard_rogue_subtlety_helmet',
      'vanguard_rogue_subtlety_shoulder',
      'vanguard_rogue_subtlety_chest',
      'vanguard_rogue_subtlety_legs',
      'vanguard_rogue_subtlety_gloves',
    ],
  },
  {
    setId: 'vanguard_priest_discipline',
    cls: 'priest',
    spec: 'discipline',
    armorType: 'cloth',
    itemIds: [
      'vanguard_priest_discipline_helmet',
      'vanguard_priest_discipline_shoulder',
      'vanguard_priest_discipline_chest',
      'vanguard_priest_discipline_legs',
      'vanguard_priest_discipline_gloves',
    ],
  },
  {
    setId: 'vanguard_priest_holy',
    cls: 'priest',
    spec: 'holy',
    armorType: 'cloth',
    itemIds: [
      'vanguard_priest_holy_helmet',
      'vanguard_priest_holy_shoulder',
      'vanguard_priest_holy_chest',
      'vanguard_priest_holy_legs',
      'vanguard_priest_holy_gloves',
    ],
  },
  {
    setId: 'vanguard_priest_shadow',
    cls: 'priest',
    spec: 'shadow',
    armorType: 'cloth',
    itemIds: [
      'vanguard_priest_shadow_helmet',
      'vanguard_priest_shadow_shoulder',
      'vanguard_priest_shadow_chest',
      'vanguard_priest_shadow_legs',
      'vanguard_priest_shadow_gloves',
    ],
  },
  {
    setId: 'vanguard_shaman_elemental',
    cls: 'shaman',
    spec: 'elemental',
    armorType: 'mail',
    itemIds: [
      'vanguard_shaman_elemental_helmet',
      'vanguard_shaman_elemental_shoulder',
      'vanguard_shaman_elemental_chest',
      'vanguard_shaman_elemental_legs',
      'vanguard_shaman_elemental_gloves',
    ],
  },
  {
    setId: 'vanguard_shaman_enhancement',
    cls: 'shaman',
    spec: 'enhancement',
    armorType: 'mail',
    itemIds: [
      'vanguard_shaman_enhancement_helmet',
      'vanguard_shaman_enhancement_shoulder',
      'vanguard_shaman_enhancement_chest',
      'vanguard_shaman_enhancement_legs',
      'vanguard_shaman_enhancement_gloves',
    ],
  },
  {
    setId: 'vanguard_shaman_restoration',
    cls: 'shaman',
    spec: 'restoration',
    armorType: 'mail',
    itemIds: [
      'vanguard_shaman_restoration_helmet',
      'vanguard_shaman_restoration_shoulder',
      'vanguard_shaman_restoration_chest',
      'vanguard_shaman_restoration_legs',
      'vanguard_shaman_restoration_gloves',
    ],
  },
  {
    setId: 'vanguard_mage_arcane',
    cls: 'mage',
    spec: 'arcane',
    armorType: 'cloth',
    itemIds: [
      'vanguard_mage_arcane_helmet',
      'vanguard_mage_arcane_shoulder',
      'vanguard_mage_arcane_chest',
      'vanguard_mage_arcane_legs',
      'vanguard_mage_arcane_gloves',
    ],
  },
  {
    setId: 'vanguard_mage_fire',
    cls: 'mage',
    spec: 'fire',
    armorType: 'cloth',
    itemIds: [
      'vanguard_mage_fire_helmet',
      'vanguard_mage_fire_shoulder',
      'vanguard_mage_fire_chest',
      'vanguard_mage_fire_legs',
      'vanguard_mage_fire_gloves',
    ],
  },
  {
    setId: 'vanguard_mage_frost',
    cls: 'mage',
    spec: 'frost',
    armorType: 'cloth',
    itemIds: [
      'vanguard_mage_frost_helmet',
      'vanguard_mage_frost_shoulder',
      'vanguard_mage_frost_chest',
      'vanguard_mage_frost_legs',
      'vanguard_mage_frost_gloves',
    ],
  },
  {
    setId: 'vanguard_warlock_affliction',
    cls: 'warlock',
    spec: 'affliction',
    armorType: 'cloth',
    itemIds: [
      'vanguard_warlock_affliction_helmet',
      'vanguard_warlock_affliction_shoulder',
      'vanguard_warlock_affliction_chest',
      'vanguard_warlock_affliction_legs',
      'vanguard_warlock_affliction_gloves',
    ],
  },
  {
    setId: 'vanguard_warlock_demonology',
    cls: 'warlock',
    spec: 'demonology',
    armorType: 'cloth',
    itemIds: [
      'vanguard_warlock_demonology_helmet',
      'vanguard_warlock_demonology_shoulder',
      'vanguard_warlock_demonology_chest',
      'vanguard_warlock_demonology_legs',
      'vanguard_warlock_demonology_gloves',
    ],
  },
  {
    setId: 'vanguard_warlock_destruction',
    cls: 'warlock',
    spec: 'destruction',
    armorType: 'cloth',
    itemIds: [
      'vanguard_warlock_destruction_helmet',
      'vanguard_warlock_destruction_shoulder',
      'vanguard_warlock_destruction_chest',
      'vanguard_warlock_destruction_legs',
      'vanguard_warlock_destruction_gloves',
    ],
  },
  {
    setId: 'vanguard_druid_balance',
    cls: 'druid',
    spec: 'balance',
    armorType: 'leather',
    itemIds: [
      'vanguard_druid_balance_helmet',
      'vanguard_druid_balance_shoulder',
      'vanguard_druid_balance_chest',
      'vanguard_druid_balance_legs',
      'vanguard_druid_balance_gloves',
    ],
  },
  {
    setId: 'vanguard_druid_feral',
    cls: 'druid',
    spec: 'feral',
    armorType: 'leather',
    itemIds: [
      'vanguard_druid_feral_helmet',
      'vanguard_druid_feral_shoulder',
      'vanguard_druid_feral_chest',
      'vanguard_druid_feral_legs',
      'vanguard_druid_feral_gloves',
    ],
  },
  {
    setId: 'vanguard_druid_restoration',
    cls: 'druid',
    spec: 'restoration',
    armorType: 'leather',
    itemIds: [
      'vanguard_druid_restoration_helmet',
      'vanguard_druid_restoration_shoulder',
      'vanguard_druid_restoration_chest',
      'vanguard_druid_restoration_legs',
      'vanguard_druid_restoration_gloves',
    ],
  },
];

export const SEASON2_WEAPON_IDS: readonly string[] = [
  'vanguard_verdict_greatsword',
  'vanguard_oath_blade',
  'vanguard_fang_dagger',
  'vanguard_warstaff',
];

export const SEASON2_ITEMS: Record<string, ItemDef> = {
  vanguard_warrior_arms_helmet: {
    id: 'vanguard_warrior_arms_helmet',
    set: 'vanguard_warrior_arms',
    name: 'Bladewake Greathelm',
    kind: 'armor',
    armorType: 'mail',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 293, str: 12, sta: 7 },
    pvpOffenseRating: 46,
    pvpDefenseRating: 71,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warrior'],
    classLocked: true,
  },
  vanguard_warrior_arms_shoulder: {
    id: 'vanguard_warrior_arms_shoulder',
    set: 'vanguard_warrior_arms',
    name: 'Bladewake Pauldrons',
    kind: 'armor',
    armorType: 'mail',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 261, str: 10, sta: 6 },
    pvpOffenseRating: 40,
    pvpDefenseRating: 61,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warrior'],
    classLocked: true,
  },
  vanguard_warrior_arms_chest: {
    id: 'vanguard_warrior_arms_chest',
    set: 'vanguard_warrior_arms',
    name: 'Bladewake Hauberk',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 342, str: 15, sta: 8 },
    pvpOffenseRating: 55,
    pvpDefenseRating: 85,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warrior'],
    classLocked: true,
  },
  vanguard_warrior_arms_legs: {
    id: 'vanguard_warrior_arms_legs',
    set: 'vanguard_warrior_arms',
    name: 'Bladewake Legplates',
    kind: 'armor',
    armorType: 'mail',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 311, str: 13, sta: 7 },
    pvpOffenseRating: 48,
    pvpDefenseRating: 75,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warrior'],
    classLocked: true,
  },
  vanguard_warrior_arms_gloves: {
    id: 'vanguard_warrior_arms_gloves',
    set: 'vanguard_warrior_arms',
    name: 'Bladewake Crushers',
    kind: 'armor',
    armorType: 'mail',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 243, str: 9, sta: 6 },
    pvpOffenseRating: 37,
    pvpDefenseRating: 58,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warrior'],
    classLocked: true,
  },
  vanguard_warrior_fury_helmet: {
    id: 'vanguard_warrior_fury_helmet',
    set: 'vanguard_warrior_fury',
    name: 'Bloodmarch Visage',
    kind: 'armor',
    armorType: 'mail',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 293, str: 12, sta: 7 },
    pvpOffenseRating: 46,
    pvpDefenseRating: 71,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warrior'],
    classLocked: true,
  },
  vanguard_warrior_fury_shoulder: {
    id: 'vanguard_warrior_fury_shoulder',
    set: 'vanguard_warrior_fury',
    name: 'Bloodmarch Shoulderguards',
    kind: 'armor',
    armorType: 'mail',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 261, str: 10, sta: 6 },
    pvpOffenseRating: 40,
    pvpDefenseRating: 61,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warrior'],
    classLocked: true,
  },
  vanguard_warrior_fury_chest: {
    id: 'vanguard_warrior_fury_chest',
    set: 'vanguard_warrior_fury',
    name: 'Bloodmarch Chainmail',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 342, str: 15, sta: 8 },
    pvpOffenseRating: 55,
    pvpDefenseRating: 85,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warrior'],
    classLocked: true,
  },
  vanguard_warrior_fury_legs: {
    id: 'vanguard_warrior_fury_legs',
    set: 'vanguard_warrior_fury',
    name: 'Bloodmarch Leggings',
    kind: 'armor',
    armorType: 'mail',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 311, str: 13, sta: 7 },
    pvpOffenseRating: 48,
    pvpDefenseRating: 75,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warrior'],
    classLocked: true,
  },
  vanguard_warrior_fury_gloves: {
    id: 'vanguard_warrior_fury_gloves',
    set: 'vanguard_warrior_fury',
    name: 'Bloodmarch Grips',
    kind: 'armor',
    armorType: 'mail',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 243, str: 9, sta: 6 },
    pvpOffenseRating: 37,
    pvpDefenseRating: 58,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warrior'],
    classLocked: true,
  },
  vanguard_warrior_prot_helmet: {
    id: 'vanguard_warrior_prot_helmet',
    set: 'vanguard_warrior_prot',
    name: 'Ironmarch Helm',
    kind: 'armor',
    armorType: 'mail',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 293, str: 12, sta: 7 },
    pvpOffenseRating: 46,
    pvpDefenseRating: 71,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warrior'],
    classLocked: true,
  },
  vanguard_warrior_prot_shoulder: {
    id: 'vanguard_warrior_prot_shoulder',
    set: 'vanguard_warrior_prot',
    name: 'Ironmarch Spaulders',
    kind: 'armor',
    armorType: 'mail',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 261, str: 10, sta: 6 },
    pvpOffenseRating: 40,
    pvpDefenseRating: 61,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warrior'],
    classLocked: true,
  },
  vanguard_warrior_prot_chest: {
    id: 'vanguard_warrior_prot_chest',
    set: 'vanguard_warrior_prot',
    name: 'Ironmarch Chestguard',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 342, str: 15, sta: 8 },
    pvpOffenseRating: 55,
    pvpDefenseRating: 85,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warrior'],
    classLocked: true,
  },
  vanguard_warrior_prot_legs: {
    id: 'vanguard_warrior_prot_legs',
    set: 'vanguard_warrior_prot',
    name: 'Ironmarch Legguards',
    kind: 'armor',
    armorType: 'mail',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 311, str: 13, sta: 7 },
    pvpOffenseRating: 48,
    pvpDefenseRating: 75,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warrior'],
    classLocked: true,
  },
  vanguard_warrior_prot_gloves: {
    id: 'vanguard_warrior_prot_gloves',
    set: 'vanguard_warrior_prot',
    name: 'Ironmarch Handguards',
    kind: 'armor',
    armorType: 'mail',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 243, str: 9, sta: 6 },
    pvpOffenseRating: 37,
    pvpDefenseRating: 58,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warrior'],
    classLocked: true,
  },
  vanguard_paladin_holy_helmet: {
    id: 'vanguard_paladin_holy_helmet',
    set: 'vanguard_paladin_holy',
    name: 'Sunvigil Circlet',
    kind: 'armor',
    armorType: 'mail',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 293, int: 11, sta: 7, spi: 8 },
    pvpOffenseRating: 46,
    pvpDefenseRating: 71,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['paladin'],
    classLocked: true,
  },
  vanguard_paladin_holy_shoulder: {
    id: 'vanguard_paladin_holy_shoulder',
    set: 'vanguard_paladin_holy',
    name: 'Sunvigil Mantle',
    kind: 'armor',
    armorType: 'mail',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 261, int: 10, sta: 6, spi: 6 },
    pvpOffenseRating: 40,
    pvpDefenseRating: 61,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['paladin'],
    classLocked: true,
  },
  vanguard_paladin_holy_chest: {
    id: 'vanguard_paladin_holy_chest',
    set: 'vanguard_paladin_holy',
    name: 'Sunvigil Hauberk',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 342, int: 14, sta: 8, spi: 9 },
    pvpOffenseRating: 55,
    pvpDefenseRating: 85,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['paladin'],
    classLocked: true,
  },
  vanguard_paladin_holy_legs: {
    id: 'vanguard_paladin_holy_legs',
    set: 'vanguard_paladin_holy',
    name: 'Sunvigil Legmail',
    kind: 'armor',
    armorType: 'mail',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 311, int: 12, sta: 7, spi: 8 },
    pvpOffenseRating: 48,
    pvpDefenseRating: 75,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['paladin'],
    classLocked: true,
  },
  vanguard_paladin_holy_gloves: {
    id: 'vanguard_paladin_holy_gloves',
    set: 'vanguard_paladin_holy',
    name: 'Sunvigil Gloves',
    kind: 'armor',
    armorType: 'mail',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 243, int: 9, sta: 6, spi: 6 },
    pvpOffenseRating: 37,
    pvpDefenseRating: 58,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['paladin'],
    classLocked: true,
  },
  vanguard_paladin_protection_helmet: {
    id: 'vanguard_paladin_protection_helmet',
    set: 'vanguard_paladin_protection',
    name: 'Shieldvow Helm',
    kind: 'armor',
    armorType: 'mail',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 293, str: 12, sta: 7 },
    pvpOffenseRating: 46,
    pvpDefenseRating: 71,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['paladin'],
    classLocked: true,
  },
  vanguard_paladin_protection_shoulder: {
    id: 'vanguard_paladin_protection_shoulder',
    set: 'vanguard_paladin_protection',
    name: 'Shieldvow Pauldrons',
    kind: 'armor',
    armorType: 'mail',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 261, str: 10, sta: 6 },
    pvpOffenseRating: 40,
    pvpDefenseRating: 61,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['paladin'],
    classLocked: true,
  },
  vanguard_paladin_protection_chest: {
    id: 'vanguard_paladin_protection_chest',
    set: 'vanguard_paladin_protection',
    name: 'Shieldvow Breastplate',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 342, str: 15, sta: 8 },
    pvpOffenseRating: 55,
    pvpDefenseRating: 85,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['paladin'],
    classLocked: true,
  },
  vanguard_paladin_protection_legs: {
    id: 'vanguard_paladin_protection_legs',
    set: 'vanguard_paladin_protection',
    name: 'Shieldvow Legplates',
    kind: 'armor',
    armorType: 'mail',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 311, str: 13, sta: 7 },
    pvpOffenseRating: 48,
    pvpDefenseRating: 75,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['paladin'],
    classLocked: true,
  },
  vanguard_paladin_protection_gloves: {
    id: 'vanguard_paladin_protection_gloves',
    set: 'vanguard_paladin_protection',
    name: 'Shieldvow Gauntlets',
    kind: 'armor',
    armorType: 'mail',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 243, str: 9, sta: 6 },
    pvpOffenseRating: 37,
    pvpDefenseRating: 58,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['paladin'],
    classLocked: true,
  },
  vanguard_paladin_retribution_helmet: {
    id: 'vanguard_paladin_retribution_helmet',
    set: 'vanguard_paladin_retribution',
    name: 'Lightbrand Crown',
    kind: 'armor',
    armorType: 'mail',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 293, str: 12, sta: 7 },
    pvpOffenseRating: 46,
    pvpDefenseRating: 71,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['paladin'],
    classLocked: true,
  },
  vanguard_paladin_retribution_shoulder: {
    id: 'vanguard_paladin_retribution_shoulder',
    set: 'vanguard_paladin_retribution',
    name: 'Lightbrand Spaulders',
    kind: 'armor',
    armorType: 'mail',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 261, str: 10, sta: 6 },
    pvpOffenseRating: 40,
    pvpDefenseRating: 61,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['paladin'],
    classLocked: true,
  },
  vanguard_paladin_retribution_chest: {
    id: 'vanguard_paladin_retribution_chest',
    set: 'vanguard_paladin_retribution',
    name: 'Lightbrand Cuirass',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 342, str: 15, sta: 8 },
    pvpOffenseRating: 55,
    pvpDefenseRating: 85,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['paladin'],
    classLocked: true,
  },
  vanguard_paladin_retribution_legs: {
    id: 'vanguard_paladin_retribution_legs',
    set: 'vanguard_paladin_retribution',
    name: 'Lightbrand Legguards',
    kind: 'armor',
    armorType: 'mail',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 311, str: 13, sta: 7 },
    pvpOffenseRating: 48,
    pvpDefenseRating: 75,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['paladin'],
    classLocked: true,
  },
  vanguard_paladin_retribution_gloves: {
    id: 'vanguard_paladin_retribution_gloves',
    set: 'vanguard_paladin_retribution',
    name: 'Lightbrand Gauntlets',
    kind: 'armor',
    armorType: 'mail',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 243, str: 9, sta: 6 },
    pvpOffenseRating: 37,
    pvpDefenseRating: 58,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['paladin'],
    classLocked: true,
  },
  vanguard_hunter_beast_mastery_helmet: {
    id: 'vanguard_hunter_beast_mastery_helmet',
    set: 'vanguard_hunter_beast_mastery',
    name: 'Packwarden Coif',
    kind: 'armor',
    armorType: 'leather',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 167, agi: 12, sta: 7 },
    pvpOffenseRating: 46,
    pvpDefenseRating: 71,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['hunter'],
    classLocked: true,
  },
  vanguard_hunter_beast_mastery_shoulder: {
    id: 'vanguard_hunter_beast_mastery_shoulder',
    set: 'vanguard_hunter_beast_mastery',
    name: 'Packwarden Spaulders',
    kind: 'armor',
    armorType: 'leather',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 149, agi: 10, sta: 6 },
    pvpOffenseRating: 40,
    pvpDefenseRating: 61,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['hunter'],
    classLocked: true,
  },
  vanguard_hunter_beast_mastery_chest: {
    id: 'vanguard_hunter_beast_mastery_chest',
    set: 'vanguard_hunter_beast_mastery',
    name: 'Packwarden Jerkin',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 194, agi: 15, sta: 8 },
    pvpOffenseRating: 55,
    pvpDefenseRating: 85,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['hunter'],
    classLocked: true,
  },
  vanguard_hunter_beast_mastery_legs: {
    id: 'vanguard_hunter_beast_mastery_legs',
    set: 'vanguard_hunter_beast_mastery',
    name: 'Packwarden Legguards',
    kind: 'armor',
    armorType: 'leather',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 176, agi: 13, sta: 7 },
    pvpOffenseRating: 48,
    pvpDefenseRating: 75,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['hunter'],
    classLocked: true,
  },
  vanguard_hunter_beast_mastery_gloves: {
    id: 'vanguard_hunter_beast_mastery_gloves',
    set: 'vanguard_hunter_beast_mastery',
    name: 'Packwarden Gauntlets',
    kind: 'armor',
    armorType: 'leather',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 135, agi: 9, sta: 6 },
    pvpOffenseRating: 37,
    pvpDefenseRating: 58,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['hunter'],
    classLocked: true,
  },
  vanguard_hunter_marksmanship_helmet: {
    id: 'vanguard_hunter_marksmanship_helmet',
    set: 'vanguard_hunter_marksmanship',
    name: 'Farsight Coif',
    kind: 'armor',
    armorType: 'leather',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 167, agi: 12, sta: 7 },
    pvpOffenseRating: 46,
    pvpDefenseRating: 71,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['hunter'],
    classLocked: true,
  },
  vanguard_hunter_marksmanship_shoulder: {
    id: 'vanguard_hunter_marksmanship_shoulder',
    set: 'vanguard_hunter_marksmanship',
    name: 'Farsight Spaulders',
    kind: 'armor',
    armorType: 'leather',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 149, agi: 10, sta: 6 },
    pvpOffenseRating: 40,
    pvpDefenseRating: 61,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['hunter'],
    classLocked: true,
  },
  vanguard_hunter_marksmanship_chest: {
    id: 'vanguard_hunter_marksmanship_chest',
    set: 'vanguard_hunter_marksmanship',
    name: 'Farsight Jerkin',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 194, agi: 15, sta: 8 },
    pvpOffenseRating: 55,
    pvpDefenseRating: 85,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['hunter'],
    classLocked: true,
  },
  vanguard_hunter_marksmanship_legs: {
    id: 'vanguard_hunter_marksmanship_legs',
    set: 'vanguard_hunter_marksmanship',
    name: 'Farsight Legguards',
    kind: 'armor',
    armorType: 'leather',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 176, agi: 13, sta: 7 },
    pvpOffenseRating: 48,
    pvpDefenseRating: 75,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['hunter'],
    classLocked: true,
  },
  vanguard_hunter_marksmanship_gloves: {
    id: 'vanguard_hunter_marksmanship_gloves',
    set: 'vanguard_hunter_marksmanship',
    name: 'Farsight Gauntlets',
    kind: 'armor',
    armorType: 'leather',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 135, agi: 9, sta: 6 },
    pvpOffenseRating: 37,
    pvpDefenseRating: 58,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['hunter'],
    classLocked: true,
  },
  vanguard_hunter_survival_helmet: {
    id: 'vanguard_hunter_survival_helmet',
    set: 'vanguard_hunter_survival',
    name: 'Snaretooth Coif',
    kind: 'armor',
    armorType: 'leather',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 167, agi: 12, sta: 7 },
    pvpOffenseRating: 46,
    pvpDefenseRating: 71,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['hunter'],
    classLocked: true,
  },
  vanguard_hunter_survival_shoulder: {
    id: 'vanguard_hunter_survival_shoulder',
    set: 'vanguard_hunter_survival',
    name: 'Snaretooth Spaulders',
    kind: 'armor',
    armorType: 'leather',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 149, agi: 10, sta: 6 },
    pvpOffenseRating: 40,
    pvpDefenseRating: 61,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['hunter'],
    classLocked: true,
  },
  vanguard_hunter_survival_chest: {
    id: 'vanguard_hunter_survival_chest',
    set: 'vanguard_hunter_survival',
    name: 'Snaretooth Jerkin',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 194, agi: 15, sta: 8 },
    pvpOffenseRating: 55,
    pvpDefenseRating: 85,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['hunter'],
    classLocked: true,
  },
  vanguard_hunter_survival_legs: {
    id: 'vanguard_hunter_survival_legs',
    set: 'vanguard_hunter_survival',
    name: 'Snaretooth Legguards',
    kind: 'armor',
    armorType: 'leather',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 176, agi: 13, sta: 7 },
    pvpOffenseRating: 48,
    pvpDefenseRating: 75,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['hunter'],
    classLocked: true,
  },
  vanguard_hunter_survival_gloves: {
    id: 'vanguard_hunter_survival_gloves',
    set: 'vanguard_hunter_survival',
    name: 'Snaretooth Gauntlets',
    kind: 'armor',
    armorType: 'leather',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 135, agi: 9, sta: 6 },
    pvpOffenseRating: 37,
    pvpDefenseRating: 58,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['hunter'],
    classLocked: true,
  },
  vanguard_rogue_assassination_helmet: {
    id: 'vanguard_rogue_assassination_helmet',
    set: 'vanguard_rogue_assassination',
    name: 'Nightcut Hood',
    kind: 'armor',
    armorType: 'leather',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 167, agi: 12, sta: 7 },
    pvpOffenseRating: 46,
    pvpDefenseRating: 71,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['rogue'],
    classLocked: true,
  },
  vanguard_rogue_assassination_shoulder: {
    id: 'vanguard_rogue_assassination_shoulder',
    set: 'vanguard_rogue_assassination',
    name: 'Nightcut Shoulderpads',
    kind: 'armor',
    armorType: 'leather',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 149, agi: 10, sta: 6 },
    pvpOffenseRating: 40,
    pvpDefenseRating: 61,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['rogue'],
    classLocked: true,
  },
  vanguard_rogue_assassination_chest: {
    id: 'vanguard_rogue_assassination_chest',
    set: 'vanguard_rogue_assassination',
    name: 'Nightcut Tunic',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 194, agi: 15, sta: 8 },
    pvpOffenseRating: 55,
    pvpDefenseRating: 85,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['rogue'],
    classLocked: true,
  },
  vanguard_rogue_assassination_legs: {
    id: 'vanguard_rogue_assassination_legs',
    set: 'vanguard_rogue_assassination',
    name: 'Nightcut Breeches',
    kind: 'armor',
    armorType: 'leather',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 176, agi: 13, sta: 7 },
    pvpOffenseRating: 48,
    pvpDefenseRating: 75,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['rogue'],
    classLocked: true,
  },
  vanguard_rogue_assassination_gloves: {
    id: 'vanguard_rogue_assassination_gloves',
    set: 'vanguard_rogue_assassination',
    name: 'Nightcut Gloves',
    kind: 'armor',
    armorType: 'leather',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 135, agi: 9, sta: 6 },
    pvpOffenseRating: 37,
    pvpDefenseRating: 58,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['rogue'],
    classLocked: true,
  },
  vanguard_rogue_combat_helmet: {
    id: 'vanguard_rogue_combat_helmet',
    set: 'vanguard_rogue_combat',
    name: 'Brawlmark Hood',
    kind: 'armor',
    armorType: 'leather',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 167, agi: 12, sta: 7 },
    pvpOffenseRating: 46,
    pvpDefenseRating: 71,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['rogue'],
    classLocked: true,
  },
  vanguard_rogue_combat_shoulder: {
    id: 'vanguard_rogue_combat_shoulder',
    set: 'vanguard_rogue_combat',
    name: 'Brawlmark Shoulderpads',
    kind: 'armor',
    armorType: 'leather',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 149, agi: 10, sta: 6 },
    pvpOffenseRating: 40,
    pvpDefenseRating: 61,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['rogue'],
    classLocked: true,
  },
  vanguard_rogue_combat_chest: {
    id: 'vanguard_rogue_combat_chest',
    set: 'vanguard_rogue_combat',
    name: 'Brawlmark Tunic',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 194, agi: 15, sta: 8 },
    pvpOffenseRating: 55,
    pvpDefenseRating: 85,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['rogue'],
    classLocked: true,
  },
  vanguard_rogue_combat_legs: {
    id: 'vanguard_rogue_combat_legs',
    set: 'vanguard_rogue_combat',
    name: 'Brawlmark Breeches',
    kind: 'armor',
    armorType: 'leather',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 176, agi: 13, sta: 7 },
    pvpOffenseRating: 48,
    pvpDefenseRating: 75,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['rogue'],
    classLocked: true,
  },
  vanguard_rogue_combat_gloves: {
    id: 'vanguard_rogue_combat_gloves',
    set: 'vanguard_rogue_combat',
    name: 'Brawlmark Gloves',
    kind: 'armor',
    armorType: 'leather',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 135, agi: 9, sta: 6 },
    pvpOffenseRating: 37,
    pvpDefenseRating: 58,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['rogue'],
    classLocked: true,
  },
  vanguard_rogue_subtlety_helmet: {
    id: 'vanguard_rogue_subtlety_helmet',
    set: 'vanguard_rogue_subtlety',
    name: 'Shadewalk Hood',
    kind: 'armor',
    armorType: 'leather',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 167, agi: 12, sta: 7 },
    pvpOffenseRating: 46,
    pvpDefenseRating: 71,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['rogue'],
    classLocked: true,
  },
  vanguard_rogue_subtlety_shoulder: {
    id: 'vanguard_rogue_subtlety_shoulder',
    set: 'vanguard_rogue_subtlety',
    name: 'Shadewalk Shoulderpads',
    kind: 'armor',
    armorType: 'leather',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 149, agi: 10, sta: 6 },
    pvpOffenseRating: 40,
    pvpDefenseRating: 61,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['rogue'],
    classLocked: true,
  },
  vanguard_rogue_subtlety_chest: {
    id: 'vanguard_rogue_subtlety_chest',
    set: 'vanguard_rogue_subtlety',
    name: 'Shadewalk Tunic',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 194, agi: 15, sta: 8 },
    pvpOffenseRating: 55,
    pvpDefenseRating: 85,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['rogue'],
    classLocked: true,
  },
  vanguard_rogue_subtlety_legs: {
    id: 'vanguard_rogue_subtlety_legs',
    set: 'vanguard_rogue_subtlety',
    name: 'Shadewalk Breeches',
    kind: 'armor',
    armorType: 'leather',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 176, agi: 13, sta: 7 },
    pvpOffenseRating: 48,
    pvpDefenseRating: 75,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['rogue'],
    classLocked: true,
  },
  vanguard_rogue_subtlety_gloves: {
    id: 'vanguard_rogue_subtlety_gloves',
    set: 'vanguard_rogue_subtlety',
    name: 'Shadewalk Gloves',
    kind: 'armor',
    armorType: 'leather',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 135, agi: 9, sta: 6 },
    pvpOffenseRating: 37,
    pvpDefenseRating: 58,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['rogue'],
    classLocked: true,
  },
  vanguard_priest_discipline_helmet: {
    id: 'vanguard_priest_discipline_helmet',
    set: 'vanguard_priest_discipline',
    name: 'Veilpsalm Cowl',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 81, int: 11, sta: 7, spi: 8 },
    pvpOffenseRating: 46,
    pvpDefenseRating: 71,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['priest'],
    classLocked: true,
  },
  vanguard_priest_discipline_shoulder: {
    id: 'vanguard_priest_discipline_shoulder',
    set: 'vanguard_priest_discipline',
    name: 'Veilpsalm Mantle',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 72, int: 10, sta: 6, spi: 6 },
    pvpOffenseRating: 40,
    pvpDefenseRating: 61,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['priest'],
    classLocked: true,
  },
  vanguard_priest_discipline_chest: {
    id: 'vanguard_priest_discipline_chest',
    set: 'vanguard_priest_discipline',
    name: 'Veilpsalm Robe',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 95, int: 14, sta: 8, spi: 9 },
    pvpOffenseRating: 55,
    pvpDefenseRating: 85,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['priest'],
    classLocked: true,
  },
  vanguard_priest_discipline_legs: {
    id: 'vanguard_priest_discipline_legs',
    set: 'vanguard_priest_discipline',
    name: 'Veilpsalm Leggings',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 86, int: 12, sta: 7, spi: 8 },
    pvpOffenseRating: 48,
    pvpDefenseRating: 75,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['priest'],
    classLocked: true,
  },
  vanguard_priest_discipline_gloves: {
    id: 'vanguard_priest_discipline_gloves',
    set: 'vanguard_priest_discipline',
    name: 'Veilpsalm Handwraps',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 68, int: 9, sta: 6, spi: 6 },
    pvpOffenseRating: 37,
    pvpDefenseRating: 58,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['priest'],
    classLocked: true,
  },
  vanguard_priest_holy_helmet: {
    id: 'vanguard_priest_holy_helmet',
    set: 'vanguard_priest_holy',
    name: 'Gracewing Cowl',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 81, int: 11, sta: 7, spi: 8 },
    pvpOffenseRating: 46,
    pvpDefenseRating: 71,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['priest'],
    classLocked: true,
  },
  vanguard_priest_holy_shoulder: {
    id: 'vanguard_priest_holy_shoulder',
    set: 'vanguard_priest_holy',
    name: 'Gracewing Mantle',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 72, int: 10, sta: 6, spi: 6 },
    pvpOffenseRating: 40,
    pvpDefenseRating: 61,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['priest'],
    classLocked: true,
  },
  vanguard_priest_holy_chest: {
    id: 'vanguard_priest_holy_chest',
    set: 'vanguard_priest_holy',
    name: 'Gracewing Robe',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 95, int: 14, sta: 8, spi: 9 },
    pvpOffenseRating: 55,
    pvpDefenseRating: 85,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['priest'],
    classLocked: true,
  },
  vanguard_priest_holy_legs: {
    id: 'vanguard_priest_holy_legs',
    set: 'vanguard_priest_holy',
    name: 'Gracewing Leggings',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 86, int: 12, sta: 7, spi: 8 },
    pvpOffenseRating: 48,
    pvpDefenseRating: 75,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['priest'],
    classLocked: true,
  },
  vanguard_priest_holy_gloves: {
    id: 'vanguard_priest_holy_gloves',
    set: 'vanguard_priest_holy',
    name: 'Gracewing Handwraps',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 68, int: 9, sta: 6, spi: 6 },
    pvpOffenseRating: 37,
    pvpDefenseRating: 58,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['priest'],
    classLocked: true,
  },
  vanguard_priest_shadow_helmet: {
    id: 'vanguard_priest_shadow_helmet',
    set: 'vanguard_priest_shadow',
    name: 'Duskhymn Cowl',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 81, int: 14, sta: 7, spi: 5 },
    pvpOffenseRating: 46,
    pvpDefenseRating: 71,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['priest'],
    classLocked: true,
  },
  vanguard_priest_shadow_shoulder: {
    id: 'vanguard_priest_shadow_shoulder',
    set: 'vanguard_priest_shadow',
    name: 'Duskhymn Mantle',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 72, int: 12, sta: 6, spi: 4 },
    pvpOffenseRating: 40,
    pvpDefenseRating: 61,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['priest'],
    classLocked: true,
  },
  vanguard_priest_shadow_chest: {
    id: 'vanguard_priest_shadow_chest',
    set: 'vanguard_priest_shadow',
    name: 'Duskhymn Robe',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 95, int: 17, sta: 8, spi: 6 },
    pvpOffenseRating: 55,
    pvpDefenseRating: 85,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['priest'],
    classLocked: true,
  },
  vanguard_priest_shadow_legs: {
    id: 'vanguard_priest_shadow_legs',
    set: 'vanguard_priest_shadow',
    name: 'Duskhymn Leggings',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 86, int: 15, sta: 7, spi: 5 },
    pvpOffenseRating: 48,
    pvpDefenseRating: 75,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['priest'],
    classLocked: true,
  },
  vanguard_priest_shadow_gloves: {
    id: 'vanguard_priest_shadow_gloves',
    set: 'vanguard_priest_shadow',
    name: 'Duskhymn Handwraps',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 68, int: 11, sta: 6, spi: 4 },
    pvpOffenseRating: 37,
    pvpDefenseRating: 58,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['priest'],
    classLocked: true,
  },
  vanguard_shaman_elemental_helmet: {
    id: 'vanguard_shaman_elemental_helmet',
    set: 'vanguard_shaman_elemental',
    name: 'Tempestwrit Coif',
    kind: 'armor',
    armorType: 'mail',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 293, int: 14, sta: 7, spi: 5 },
    pvpOffenseRating: 46,
    pvpDefenseRating: 71,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['shaman'],
    classLocked: true,
  },
  vanguard_shaman_elemental_shoulder: {
    id: 'vanguard_shaman_elemental_shoulder',
    set: 'vanguard_shaman_elemental',
    name: 'Tempestwrit Pauldrons',
    kind: 'armor',
    armorType: 'mail',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 261, int: 12, sta: 6, spi: 4 },
    pvpOffenseRating: 40,
    pvpDefenseRating: 61,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['shaman'],
    classLocked: true,
  },
  vanguard_shaman_elemental_chest: {
    id: 'vanguard_shaman_elemental_chest',
    set: 'vanguard_shaman_elemental',
    name: 'Tempestwrit Hauberk',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 342, int: 17, sta: 8, spi: 6 },
    pvpOffenseRating: 55,
    pvpDefenseRating: 85,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['shaman'],
    classLocked: true,
  },
  vanguard_shaman_elemental_legs: {
    id: 'vanguard_shaman_elemental_legs',
    set: 'vanguard_shaman_elemental',
    name: 'Tempestwrit Legmail',
    kind: 'armor',
    armorType: 'mail',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 311, int: 15, sta: 7, spi: 5 },
    pvpOffenseRating: 48,
    pvpDefenseRating: 75,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['shaman'],
    classLocked: true,
  },
  vanguard_shaman_elemental_gloves: {
    id: 'vanguard_shaman_elemental_gloves',
    set: 'vanguard_shaman_elemental',
    name: 'Tempestwrit Gauntlets',
    kind: 'armor',
    armorType: 'mail',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 243, int: 11, sta: 6, spi: 4 },
    pvpOffenseRating: 37,
    pvpDefenseRating: 58,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['shaman'],
    classLocked: true,
  },
  vanguard_shaman_enhancement_helmet: {
    id: 'vanguard_shaman_enhancement_helmet',
    set: 'vanguard_shaman_enhancement',
    name: 'Galeborn Helm',
    kind: 'armor',
    armorType: 'mail',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 293, agi: 12, sta: 7 },
    pvpOffenseRating: 46,
    pvpDefenseRating: 71,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['shaman'],
    classLocked: true,
  },
  vanguard_shaman_enhancement_shoulder: {
    id: 'vanguard_shaman_enhancement_shoulder',
    set: 'vanguard_shaman_enhancement',
    name: 'Galeborn Spaulders',
    kind: 'armor',
    armorType: 'mail',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 261, agi: 10, sta: 6 },
    pvpOffenseRating: 40,
    pvpDefenseRating: 61,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['shaman'],
    classLocked: true,
  },
  vanguard_shaman_enhancement_chest: {
    id: 'vanguard_shaman_enhancement_chest',
    set: 'vanguard_shaman_enhancement',
    name: 'Galeborn Chainmail',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 342, agi: 15, sta: 8 },
    pvpOffenseRating: 55,
    pvpDefenseRating: 85,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['shaman'],
    classLocked: true,
  },
  vanguard_shaman_enhancement_legs: {
    id: 'vanguard_shaman_enhancement_legs',
    set: 'vanguard_shaman_enhancement',
    name: 'Galeborn Legguards',
    kind: 'armor',
    armorType: 'mail',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 311, agi: 13, sta: 7 },
    pvpOffenseRating: 48,
    pvpDefenseRating: 75,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['shaman'],
    classLocked: true,
  },
  vanguard_shaman_enhancement_gloves: {
    id: 'vanguard_shaman_enhancement_gloves',
    set: 'vanguard_shaman_enhancement',
    name: 'Galeborn Grips',
    kind: 'armor',
    armorType: 'mail',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 243, agi: 9, sta: 6 },
    pvpOffenseRating: 37,
    pvpDefenseRating: 58,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['shaman'],
    classLocked: true,
  },
  vanguard_shaman_restoration_helmet: {
    id: 'vanguard_shaman_restoration_helmet',
    set: 'vanguard_shaman_restoration',
    name: 'Brineward Circlet',
    kind: 'armor',
    armorType: 'mail',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 293, int: 11, sta: 7, spi: 8 },
    pvpOffenseRating: 46,
    pvpDefenseRating: 71,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['shaman'],
    classLocked: true,
  },
  vanguard_shaman_restoration_shoulder: {
    id: 'vanguard_shaman_restoration_shoulder',
    set: 'vanguard_shaman_restoration',
    name: 'Brineward Mantle',
    kind: 'armor',
    armorType: 'mail',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 261, int: 10, sta: 6, spi: 6 },
    pvpOffenseRating: 40,
    pvpDefenseRating: 61,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['shaman'],
    classLocked: true,
  },
  vanguard_shaman_restoration_chest: {
    id: 'vanguard_shaman_restoration_chest',
    set: 'vanguard_shaman_restoration',
    name: 'Brineward Hauberk',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 342, int: 14, sta: 8, spi: 9 },
    pvpOffenseRating: 55,
    pvpDefenseRating: 85,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['shaman'],
    classLocked: true,
  },
  vanguard_shaman_restoration_legs: {
    id: 'vanguard_shaman_restoration_legs',
    set: 'vanguard_shaman_restoration',
    name: 'Brineward Kilt',
    kind: 'armor',
    armorType: 'mail',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 311, int: 12, sta: 7, spi: 8 },
    pvpOffenseRating: 48,
    pvpDefenseRating: 75,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['shaman'],
    classLocked: true,
  },
  vanguard_shaman_restoration_gloves: {
    id: 'vanguard_shaman_restoration_gloves',
    set: 'vanguard_shaman_restoration',
    name: 'Brineward Handwraps',
    kind: 'armor',
    armorType: 'mail',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 243, int: 9, sta: 6, spi: 6 },
    pvpOffenseRating: 37,
    pvpDefenseRating: 58,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['shaman'],
    classLocked: true,
  },
  vanguard_mage_arcane_helmet: {
    id: 'vanguard_mage_arcane_helmet',
    set: 'vanguard_mage_arcane',
    name: "Hourbinder's Hood",
    kind: 'armor',
    armorType: 'cloth',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 81, int: 11, sta: 7, spi: 8 },
    pvpOffenseRating: 46,
    pvpDefenseRating: 71,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['mage'],
    classLocked: true,
  },
  vanguard_mage_arcane_shoulder: {
    id: 'vanguard_mage_arcane_shoulder',
    set: 'vanguard_mage_arcane',
    name: "Hourbinder's Amice",
    kind: 'armor',
    armorType: 'cloth',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 72, int: 10, sta: 6, spi: 6 },
    pvpOffenseRating: 40,
    pvpDefenseRating: 61,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['mage'],
    classLocked: true,
  },
  vanguard_mage_arcane_chest: {
    id: 'vanguard_mage_arcane_chest',
    set: 'vanguard_mage_arcane',
    name: "Hourbinder's Robe",
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 95, int: 14, sta: 8, spi: 9 },
    pvpOffenseRating: 55,
    pvpDefenseRating: 85,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['mage'],
    classLocked: true,
  },
  vanguard_mage_arcane_legs: {
    id: 'vanguard_mage_arcane_legs',
    set: 'vanguard_mage_arcane',
    name: "Hourbinder's Trousers",
    kind: 'armor',
    armorType: 'cloth',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 86, int: 12, sta: 7, spi: 8 },
    pvpOffenseRating: 48,
    pvpDefenseRating: 75,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['mage'],
    classLocked: true,
  },
  vanguard_mage_arcane_gloves: {
    id: 'vanguard_mage_arcane_gloves',
    set: 'vanguard_mage_arcane',
    name: "Hourbinder's Gloves",
    kind: 'armor',
    armorType: 'cloth',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 68, int: 9, sta: 6, spi: 6 },
    pvpOffenseRating: 37,
    pvpDefenseRating: 58,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['mage'],
    classLocked: true,
  },
  vanguard_mage_fire_helmet: {
    id: 'vanguard_mage_fire_helmet',
    set: 'vanguard_mage_fire',
    name: 'Emberlash Cowl',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 81, int: 14, sta: 7, spi: 5 },
    pvpOffenseRating: 46,
    pvpDefenseRating: 71,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['mage'],
    classLocked: true,
  },
  vanguard_mage_fire_shoulder: {
    id: 'vanguard_mage_fire_shoulder',
    set: 'vanguard_mage_fire',
    name: 'Emberlash Mantle',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 72, int: 12, sta: 6, spi: 4 },
    pvpOffenseRating: 40,
    pvpDefenseRating: 61,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['mage'],
    classLocked: true,
  },
  vanguard_mage_fire_chest: {
    id: 'vanguard_mage_fire_chest',
    set: 'vanguard_mage_fire',
    name: 'Emberlash Robes',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 95, int: 17, sta: 8, spi: 6 },
    pvpOffenseRating: 55,
    pvpDefenseRating: 85,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['mage'],
    classLocked: true,
  },
  vanguard_mage_fire_legs: {
    id: 'vanguard_mage_fire_legs',
    set: 'vanguard_mage_fire',
    name: 'Emberlash Leggings',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 86, int: 15, sta: 7, spi: 5 },
    pvpOffenseRating: 48,
    pvpDefenseRating: 75,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['mage'],
    classLocked: true,
  },
  vanguard_mage_fire_gloves: {
    id: 'vanguard_mage_fire_gloves',
    set: 'vanguard_mage_fire',
    name: 'Emberlash Gloves',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 68, int: 11, sta: 6, spi: 4 },
    pvpOffenseRating: 37,
    pvpDefenseRating: 58,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['mage'],
    classLocked: true,
  },
  vanguard_mage_frost_helmet: {
    id: 'vanguard_mage_frost_helmet',
    set: 'vanguard_mage_frost',
    name: 'Rimewarden Hood',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 81, int: 14, sta: 7, spi: 5 },
    pvpOffenseRating: 46,
    pvpDefenseRating: 71,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['mage'],
    classLocked: true,
  },
  vanguard_mage_frost_shoulder: {
    id: 'vanguard_mage_frost_shoulder',
    set: 'vanguard_mage_frost',
    name: 'Rimewarden Shoulderpads',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 72, int: 12, sta: 6, spi: 4 },
    pvpOffenseRating: 40,
    pvpDefenseRating: 61,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['mage'],
    classLocked: true,
  },
  vanguard_mage_frost_chest: {
    id: 'vanguard_mage_frost_chest',
    set: 'vanguard_mage_frost',
    name: 'Rimewarden Vestment',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 95, int: 17, sta: 8, spi: 6 },
    pvpOffenseRating: 55,
    pvpDefenseRating: 85,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['mage'],
    classLocked: true,
  },
  vanguard_mage_frost_legs: {
    id: 'vanguard_mage_frost_legs',
    set: 'vanguard_mage_frost',
    name: 'Rimewarden Legwraps',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 86, int: 15, sta: 7, spi: 5 },
    pvpOffenseRating: 48,
    pvpDefenseRating: 75,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['mage'],
    classLocked: true,
  },
  vanguard_mage_frost_gloves: {
    id: 'vanguard_mage_frost_gloves',
    set: 'vanguard_mage_frost',
    name: 'Rimewarden Mitts',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 68, int: 11, sta: 6, spi: 4 },
    pvpOffenseRating: 37,
    pvpDefenseRating: 58,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['mage'],
    classLocked: true,
  },
  vanguard_warlock_affliction_helmet: {
    id: 'vanguard_warlock_affliction_helmet',
    set: 'vanguard_warlock_affliction',
    name: 'Dreadquill Hood',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 81, int: 14, sta: 7, spi: 5 },
    pvpOffenseRating: 46,
    pvpDefenseRating: 71,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warlock'],
    classLocked: true,
  },
  vanguard_warlock_affliction_shoulder: {
    id: 'vanguard_warlock_affliction_shoulder',
    set: 'vanguard_warlock_affliction',
    name: 'Dreadquill Mantle',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 72, int: 12, sta: 6, spi: 4 },
    pvpOffenseRating: 40,
    pvpDefenseRating: 61,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warlock'],
    classLocked: true,
  },
  vanguard_warlock_affliction_chest: {
    id: 'vanguard_warlock_affliction_chest',
    set: 'vanguard_warlock_affliction',
    name: 'Dreadquill Robe',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 95, int: 17, sta: 8, spi: 6 },
    pvpOffenseRating: 55,
    pvpDefenseRating: 85,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warlock'],
    classLocked: true,
  },
  vanguard_warlock_affliction_legs: {
    id: 'vanguard_warlock_affliction_legs',
    set: 'vanguard_warlock_affliction',
    name: 'Dreadquill Leggings',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 86, int: 15, sta: 7, spi: 5 },
    pvpOffenseRating: 48,
    pvpDefenseRating: 75,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warlock'],
    classLocked: true,
  },
  vanguard_warlock_affliction_gloves: {
    id: 'vanguard_warlock_affliction_gloves',
    set: 'vanguard_warlock_affliction',
    name: 'Dreadquill Handwraps',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 68, int: 11, sta: 6, spi: 4 },
    pvpOffenseRating: 37,
    pvpDefenseRating: 58,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warlock'],
    classLocked: true,
  },
  vanguard_warlock_demonology_helmet: {
    id: 'vanguard_warlock_demonology_helmet',
    set: 'vanguard_warlock_demonology',
    name: 'Marrowbound Cowl',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 81, int: 14, sta: 7, spi: 5 },
    pvpOffenseRating: 46,
    pvpDefenseRating: 71,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warlock'],
    classLocked: true,
  },
  vanguard_warlock_demonology_shoulder: {
    id: 'vanguard_warlock_demonology_shoulder',
    set: 'vanguard_warlock_demonology',
    name: 'Marrowbound Spaulders',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 72, int: 12, sta: 6, spi: 4 },
    pvpOffenseRating: 40,
    pvpDefenseRating: 61,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warlock'],
    classLocked: true,
  },
  vanguard_warlock_demonology_chest: {
    id: 'vanguard_warlock_demonology_chest',
    set: 'vanguard_warlock_demonology',
    name: 'Marrowbound Robe',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 95, int: 17, sta: 8, spi: 6 },
    pvpOffenseRating: 55,
    pvpDefenseRating: 85,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warlock'],
    classLocked: true,
  },
  vanguard_warlock_demonology_legs: {
    id: 'vanguard_warlock_demonology_legs',
    set: 'vanguard_warlock_demonology',
    name: 'Marrowbound Leggings',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 86, int: 15, sta: 7, spi: 5 },
    pvpOffenseRating: 48,
    pvpDefenseRating: 75,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warlock'],
    classLocked: true,
  },
  vanguard_warlock_demonology_gloves: {
    id: 'vanguard_warlock_demonology_gloves',
    set: 'vanguard_warlock_demonology',
    name: 'Marrowbound Grips',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 68, int: 11, sta: 6, spi: 4 },
    pvpOffenseRating: 37,
    pvpDefenseRating: 58,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warlock'],
    classLocked: true,
  },
  vanguard_warlock_destruction_helmet: {
    id: 'vanguard_warlock_destruction_helmet',
    set: 'vanguard_warlock_destruction',
    name: 'Slagcrown Hood',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 81, int: 14, sta: 7, spi: 5 },
    pvpOffenseRating: 46,
    pvpDefenseRating: 71,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warlock'],
    classLocked: true,
  },
  vanguard_warlock_destruction_shoulder: {
    id: 'vanguard_warlock_destruction_shoulder',
    set: 'vanguard_warlock_destruction',
    name: 'Slagcrown Mantle',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 72, int: 12, sta: 6, spi: 4 },
    pvpOffenseRating: 40,
    pvpDefenseRating: 61,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warlock'],
    classLocked: true,
  },
  vanguard_warlock_destruction_chest: {
    id: 'vanguard_warlock_destruction_chest',
    set: 'vanguard_warlock_destruction',
    name: 'Slagcrown Robes',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 95, int: 17, sta: 8, spi: 6 },
    pvpOffenseRating: 55,
    pvpDefenseRating: 85,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warlock'],
    classLocked: true,
  },
  vanguard_warlock_destruction_legs: {
    id: 'vanguard_warlock_destruction_legs',
    set: 'vanguard_warlock_destruction',
    name: 'Slagcrown Leggings',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 86, int: 15, sta: 7, spi: 5 },
    pvpOffenseRating: 48,
    pvpDefenseRating: 75,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warlock'],
    classLocked: true,
  },
  vanguard_warlock_destruction_gloves: {
    id: 'vanguard_warlock_destruction_gloves',
    set: 'vanguard_warlock_destruction',
    name: 'Slagcrown Gloves',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 68, int: 11, sta: 6, spi: 4 },
    pvpOffenseRating: 37,
    pvpDefenseRating: 58,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warlock'],
    classLocked: true,
  },
  vanguard_druid_balance_helmet: {
    id: 'vanguard_druid_balance_helmet',
    set: 'vanguard_druid_balance',
    name: 'Starwarden Headdress',
    kind: 'armor',
    armorType: 'leather',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 167, int: 14, sta: 7, spi: 5 },
    pvpOffenseRating: 46,
    pvpDefenseRating: 71,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['druid'],
    classLocked: true,
  },
  vanguard_druid_balance_shoulder: {
    id: 'vanguard_druid_balance_shoulder',
    set: 'vanguard_druid_balance',
    name: 'Starwarden Spaulders',
    kind: 'armor',
    armorType: 'leather',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 149, int: 12, sta: 6, spi: 4 },
    pvpOffenseRating: 40,
    pvpDefenseRating: 61,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['druid'],
    classLocked: true,
  },
  vanguard_druid_balance_chest: {
    id: 'vanguard_druid_balance_chest',
    set: 'vanguard_druid_balance',
    name: 'Starwarden Vest',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 194, int: 17, sta: 8, spi: 6 },
    pvpOffenseRating: 55,
    pvpDefenseRating: 85,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['druid'],
    classLocked: true,
  },
  vanguard_druid_balance_legs: {
    id: 'vanguard_druid_balance_legs',
    set: 'vanguard_druid_balance',
    name: 'Starwarden Breeches',
    kind: 'armor',
    armorType: 'leather',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 176, int: 15, sta: 7, spi: 5 },
    pvpOffenseRating: 48,
    pvpDefenseRating: 75,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['druid'],
    classLocked: true,
  },
  vanguard_druid_balance_gloves: {
    id: 'vanguard_druid_balance_gloves',
    set: 'vanguard_druid_balance',
    name: 'Starwarden Gloves',
    kind: 'armor',
    armorType: 'leather',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 135, int: 11, sta: 6, spi: 4 },
    pvpOffenseRating: 37,
    pvpDefenseRating: 58,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['druid'],
    classLocked: true,
  },
  vanguard_druid_feral_helmet: {
    id: 'vanguard_druid_feral_helmet',
    set: 'vanguard_druid_feral',
    name: 'Bloodmane Helm',
    kind: 'armor',
    armorType: 'leather',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 167, agi: 12, sta: 7 },
    pvpOffenseRating: 46,
    pvpDefenseRating: 71,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['druid'],
    classLocked: true,
  },
  vanguard_druid_feral_shoulder: {
    id: 'vanguard_druid_feral_shoulder',
    set: 'vanguard_druid_feral',
    name: 'Bloodmane Shoulderpads',
    kind: 'armor',
    armorType: 'leather',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 149, agi: 10, sta: 6 },
    pvpOffenseRating: 40,
    pvpDefenseRating: 61,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['druid'],
    classLocked: true,
  },
  vanguard_druid_feral_chest: {
    id: 'vanguard_druid_feral_chest',
    set: 'vanguard_druid_feral',
    name: 'Bloodmane Tunic',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 194, agi: 15, sta: 8 },
    pvpOffenseRating: 55,
    pvpDefenseRating: 85,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['druid'],
    classLocked: true,
  },
  vanguard_druid_feral_legs: {
    id: 'vanguard_druid_feral_legs',
    set: 'vanguard_druid_feral',
    name: 'Bloodmane Legguards',
    kind: 'armor',
    armorType: 'leather',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 176, agi: 13, sta: 7 },
    pvpOffenseRating: 48,
    pvpDefenseRating: 75,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['druid'],
    classLocked: true,
  },
  vanguard_druid_feral_gloves: {
    id: 'vanguard_druid_feral_gloves',
    set: 'vanguard_druid_feral',
    name: 'Bloodmane Grips',
    kind: 'armor',
    armorType: 'leather',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 135, agi: 9, sta: 6 },
    pvpOffenseRating: 37,
    pvpDefenseRating: 58,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['druid'],
    classLocked: true,
  },
  vanguard_druid_restoration_helmet: {
    id: 'vanguard_druid_restoration_helmet',
    set: 'vanguard_druid_restoration',
    name: 'Thistlebloom Crown',
    kind: 'armor',
    armorType: 'leather',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 167, int: 11, sta: 7, spi: 8 },
    pvpOffenseRating: 46,
    pvpDefenseRating: 71,
    priceHonor: 1350,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['druid'],
    classLocked: true,
  },
  vanguard_druid_restoration_shoulder: {
    id: 'vanguard_druid_restoration_shoulder',
    set: 'vanguard_druid_restoration',
    name: 'Thistlebloom Mantle',
    kind: 'armor',
    armorType: 'leather',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 149, int: 10, sta: 6, spi: 6 },
    pvpOffenseRating: 40,
    pvpDefenseRating: 61,
    priceHonor: 1050,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['druid'],
    classLocked: true,
  },
  vanguard_druid_restoration_chest: {
    id: 'vanguard_druid_restoration_chest',
    set: 'vanguard_druid_restoration',
    name: 'Thistlebloom Vest',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 194, int: 14, sta: 8, spi: 9 },
    pvpOffenseRating: 55,
    pvpDefenseRating: 85,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['druid'],
    classLocked: true,
  },
  vanguard_druid_restoration_legs: {
    id: 'vanguard_druid_restoration_legs',
    set: 'vanguard_druid_restoration',
    name: 'Thistlebloom Leggings',
    kind: 'armor',
    armorType: 'leather',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 176, int: 12, sta: 7, spi: 8 },
    pvpOffenseRating: 48,
    pvpDefenseRating: 75,
    priceHonor: 1575,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['druid'],
    classLocked: true,
  },
  vanguard_druid_restoration_gloves: {
    id: 'vanguard_druid_restoration_gloves',
    set: 'vanguard_druid_restoration',
    name: 'Thistlebloom Gloves',
    kind: 'armor',
    armorType: 'leather',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 135, int: 9, sta: 6, spi: 6 },
    pvpOffenseRating: 37,
    pvpDefenseRating: 58,
    priceHonor: 825,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['druid'],
    classLocked: true,
  },
  vanguard_verdict_greatsword: {
    id: 'vanguard_verdict_greatsword',
    name: "Vanguard's Verdict",
    kind: 'weapon',
    slot: 'mainhand',
    hand: 'twohand',
    quality: 'epic',
    requiredLevel: 20,
    weapon: { min: 54, max: 81, speed: 3.4 },
    stats: { str: 19, sta: 11 },
    pvpOffenseRating: 73,
    pvpDefenseRating: 112,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warrior', 'paladin', 'shaman'],
  },
  vanguard_oath_blade: {
    id: 'vanguard_oath_blade',
    name: "Vanguard's Oath",
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'epic',
    requiredLevel: 20,
    weapon: { min: 36, max: 54, speed: 2.6 },
    stats: { str: 15, sta: 8 },
    pvpOffenseRating: 55,
    pvpDefenseRating: 85,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warrior', 'paladin', 'shaman'],
  },
  vanguard_fang_dagger: {
    id: 'vanguard_fang_dagger',
    name: "Vanguard's Fang",
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'epic',
    requiredLevel: 20,
    weapon: { min: 25, max: 37, speed: 1.8, dagger: true },
    stats: { agi: 15, sta: 8 },
    pvpOffenseRating: 55,
    pvpDefenseRating: 85,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['rogue', 'hunter', 'druid'],
  },
  vanguard_warstaff: {
    id: 'vanguard_warstaff',
    name: "Vanguard's Warstaff",
    kind: 'weapon',
    slot: 'mainhand',
    hand: 'twohand',
    quality: 'epic',
    requiredLevel: 20,
    weapon: { min: 47, max: 71, speed: 3 },
    stats: { int: 23, sta: 11, spi: 7 },
    pvpOffenseRating: 73,
    pvpDefenseRating: 112,
    priceHonor: 1800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['mage', 'priest', 'warlock', 'shaman', 'paladin', 'druid'],
  },
};

export const SEASON2_STOCK: readonly string[] = Object.keys(SEASON2_ITEMS);
